### ISSUE TITLE
Cannot load dbfload.py

### ISSUE THREAD

**Issue by ghost** [UrbanDS/Python-Tool-Sample-py3#6]
I was trying to open dbfload from the directory, but the following error appears: 

>python dbfload.py
Traceback (most recent call last):
  File "dbfload.py", line 261, in <module>
    d1 = DbfLoader('data/geoda/nat.dbf')
  File "dbfload.py", line 65, in __init__
    if (dbfFileName): self.loadDbfFileName(dbfFileName)
  File "dbfload.py", line 70, in loadDbfFileName
    dbfs = open(dbfFileName, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/geoda/nat.dbf'

**Comment by dujiaxin** [comment]
Hi, there are several questions you might help me answer to figure out what really happens.
 First, to start GUI, you need to 
`python main_menu.py`
Second, can you check if the path of nat.dbf is correct?
Can you run a pwd to make sure you are on the right relative path?

**Comment by ghost** [comment]
Hi, I started the GUI and it opened correctly. My mistake was opening the dbfload.py file first. If I am understanding correctly, the GUI uses the dbfload.py to run correctly?
